#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: launchpads

on:
  push:
    branches-ignore:
        - master

env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_azure_devops_pat_token: ${{ secrets.TF_VAR_azure_devops_pat_token }}
  TF_VAR_azure_devops_url_organization: ${{ secrets.TF_VAR_azure_devops_url_organization }}
  region: "westus2"

jobs:
  level0:
    name: level0
    runs-on: ubuntu-latest
    
    container:
      image: aztfmod/roverdev:2004.210909
      options: --user 0

    steps:
      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
      
      - name: Locate launchpad
        run: |
          id=$(az storage account list --query "[?tags.tfstate=='level0' && tags.workspace=='level0'] -o json | jq -r .[0].id)
          if [ "${id}" == "null" ]; then
            /tf/rover/launchpad.sh /tf/launchpads/launchpad_opensource apply -var location=${{ env.region }}
          fi
            
  launchpad:
    name: Launchpad tests
    runs-on: ubuntu-latest
    
    needs: level0

    strategy:
      fail-fast: false
      matrix:
        launchpad: ["launchpad_opensource_light", "launchpad_opensource"]
        region: ["westus2"]
        convention: ["cafclassic", "cafrandom"]
    
      
    container:
      image: aztfmod/roverdev:2004.210909
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name:  setup context
        id: context
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf
          echo "ls /tf/caf" && ls -lsa /tf/caf
          ls -lsa /tmp

          job_id=${{ job.container.id }}
          workspace=${job_id:0:63}
          echo ::set-env name=TF_VAR_workspace::${workspace}

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
            
      - name: workspace      
        run: |
          /tf/rover/launchpad.sh workspace create ${TF_VAR_workspace}
  
      - name: Terraform plan
        run: |
          /tf/rover/rover.sh /tf/caf/launchpads/${{ matrix.launchpad }} plan \
              '-var location=${{ matrix.region }}' \
              '-var tags={testing-job-id="${{ github.run_id }}"}' \
              '-var convention=${{ matrix.convention }}'

      - name: Terraform apply
        run: |
          /tf/rover/rover.sh /tf/caf/launchpads/${{ matrix.launchpad }} apply \
              '-var location=${{ matrix.region }}' \
              '-var tags={testing-job-id="${{ github.run_id }}"}' \
              '-var convention=${{ matrix.convention }}'

      - name: Terraform destroy
        run: |
          /tf/rover/rover.sh /tf/caf/launchpads/${{ matrix.launchpad }} destroy \
              '-var location=${{ matrix.region }}' \
              '-var tags={testing-job-id="${{ github.run_id }}"}' \
              '-var convention=${{ matrix.convention }}'

      - name: cleanup
        run: |
          stg_name=$(az storage account list --query "[?tags.tfstate=='level0' && tags.workspace=='level0']" -o json | jq -r .[0].name)
          az storage container delete --account-name ${stg_name} --name ${TF_VAR_workspace} --auth-mode login
    
